# Generated by Django 3.2.8 on 2021-11-03 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='uploadBy',
            new_name='uploadedBy',
        ),
        migrations.AddField(
            model_name='container',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
