# Generated by Django 3.2.8 on 2021-11-04 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211103_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='dateRenewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 4, 15, 1, 6, 800622, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trademark',
            name='dateRenewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 4, 15, 2, 9, 858904, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
