# Generated by Django 3.2.8 on 2021-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211104_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademark',
            name='shelfLife',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
