# Generated by Django 3.2.8 on 2021-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211105_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='datePosted',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='trademark',
            old_name='datePosted',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='container',
            name='dateRenewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='acceptanceDoc',
            field=models.FileField(blank=True, upload_to='acceptance_docs/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='trademark_cert/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='dateRenewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
