# Generated by Django 3.2.8 on 2021-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211105_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='endorsementDoc',
            field=models.FileField(default='default.jpg', upload_to='endorsements'),
        ),
        migrations.AlterField(
            model_name='container',
            name='receiptDoc',
            field=models.FileField(default='default.jpg', upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='acceptanceDoc',
            field=models.FileField(default='default.jpg', upload_to='acceptance_docs/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='acknowledgeDoc',
            field=models.FileField(default='default.jpg', upload_to='acknowledge_docs'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='cert',
            field=models.FileField(default='default.jpg', upload_to='trademark_cert/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='renewalDoc',
            field=models.FileField(default='default.jpg', upload_to='renewalDocs'),
        ),
    ]
