# Generated by Django 3.2.8 on 2021-11-07 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211106_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademark',
            name='shelfLife',
        ),
        migrations.AlterField(
            model_name='trademark',
            name='dateRenewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
