# Generated by Django 3.2.8 on 2021-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211107_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='endorsementDoc',
            field=models.FileField(blank=True, null=True, upload_to='endorsements'),
        ),
        migrations.AlterField(
            model_name='container',
            name='receiptDoc',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='acceptanceDoc',
            field=models.FileField(blank=True, null=True, upload_to='acceptance_docs/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='acknowledgeDoc',
            field=models.FileField(blank=True, null=True, upload_to='acknowledge_docs'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='trademark_cert/'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='renewalDoc',
            field=models.FileField(blank=True, null=True, upload_to='renewalDocs'),
        ),
    ]
