# Generated by Django 3.2.8 on 2021-11-09 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_container_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='dateRenewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='container',
            name='expiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
